### ISSUE TITLE
I am not around until the beginning of August

### ISSUE THREAD

**Issue by tarsius** [tarsius/no-littering#17]
I might show up once or twice, but anything more than that would be a surprise.

@justbur please merge pull requests using your own judgement ;-)
I've also pushed #16 with some updates to the conventions. Adjust them as you see fit.

Sorry for the short notice.

Best regards,
Jonas

**Comment by justbur** [comment]
No problem. I hope it's for something fun.

**Comment by tarsius** [comment]
Yes! (Doesn't count as one of the shows ;-)

**Comment by tarsius** [comment]
I'm back.
