### ISSUE TITLE
add some var

### ISSUE THREAD

**Issue by xianghx** [tarsius/no-littering#22]
(setq persp-save-dir (var "persp-confs/"))
    (setq slime-repl-history-file (var "slime-history.eld"))
    (setq cider-history-file (var "cider-nrepl-history"))
    (setq geiser-repl-history-filename (var "geiser_history"))
    (setq geiser-racket-init-file (var "racket-geiser"))
    (setq geiser-guile-init-file (var "guile-geiser"))
    (setq wg-session-file (var "emacs_workgroups"))
    (setq session-save-file (var "session"))

**Comment by tarsius** [comment]
Please put some effort into this. Read about the conventions, then create a few commits and submit a pull request.

**Comment by piyo** [comment]
If anyone else wants to PR, this is the current state of completion, if these variables still exist.

- [X] persp-save-dir
- [ ] slime-repl-history-file
- [ ] cider-history-file
- [X] geiser-repl-history-filename
- [ ] geiser-racket-init-file
- [ ] geiser-guile-init-file
- [ ] wg-session-file
- [ ] session-save-file
