### ISSUE TITLE
Inconsistency between package and readme

### ISSUE THREAD

**Issue by therockmandolinist** [tarsius/no-littering#24]
The readme says:

>E.g. the path used for `sx-cache-directory` from the sx package is `sx/cache/`, not `sx-cache/`.

But the path used _is_ `sx-cache/`.

**Comment by tarsius** [comment]
I've fixed that by using `sx/cache/`. I think when we introduced the respective convention we just somehow forgot the change the actual configuration.

**Comment by therockmandolinist** [comment]
@tarsius I think I would actually argue there's no point in creating nested directories when only one is needed, could you explain the reasoning behind this convention?
