### ISSUE TITLE
Should this package set `trash-directory`?

### ISSUE THREAD

**Issue by DamienCassou** [tarsius/no-littering#31]
The default value, `nil`, is kind of cool:

> If the value is `nil`, Emacs uses a freedesktop.org-style trashcan.

**Comment by tarsius** [comment]
Yeah, we should probably remove that.

**Comment by tarsius** [comment]
@justbur What do you think?

**Comment by justbur** [comment]
I agree remove it. There's no need to define a new trash can I don't think. 

By the way, I just took a look at `move-file-to-trash` and the docstring lies. It says

```
If the function `system-move-file-to-trash' is defined, call it
 with FILENAME as an argument.
Otherwise, if `trash-directory' is non-nil, move FILENAME to that
 directory.
Otherwise, trash FILENAME using the freedesktop.org conventions,
 like the GNOME, KDE and XFCE desktop environments.  Emacs only
 moves files to \"home trash\", ignoring per-volume trashcans.
```

which sounds like it looks for `system-move-file-to-trash` first, but it doesn't. In my emacs (25.1.91.1) it looks for `trash-directory` first.

**Comment by tarsius** [comment]
Yeah, noticed that too ;-/
