### ISSUE TITLE
Should personal ispell/aspell/hunspell dictionary files be handled by no-littering?

### ISSUE THREAD

**Issue by doolio** [tarsius/no-littering#47]
I'm speaking of the files defined by `ispell-personal-dictionary`. Thoughts?

**Comment by tarsius** [comment]
Since these files can also be used outside of Emacs, I would say no.

**Comment by doolio** [comment]
Ok, I did not appreciate that point. Thanks for `no-littering` and your time. We can consider this issue closed.
